// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calc_d3_method
NumericVector calc_d3_method(LogicalVector d3_cands, NumericVector dx);
RcppExport SEXP _rdailychange_calc_d3_method(SEXP d3_candsSEXP, SEXP dxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type d3_cands(d3_candsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dx(dxSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_d3_method(d3_cands, dx));
    return rcpp_result_gen;
END_RCPP
}
// calc_d4_method
NumericVector calc_d4_method(LogicalVector d4_cands, NumericVector dx);
RcppExport SEXP _rdailychange_calc_d4_method(SEXP d4_candsSEXP, SEXP dxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type d4_cands(d4_candsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dx(dxSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_d4_method(d4_cands, dx));
    return rcpp_result_gen;
END_RCPP
}
// calc_d5_method
NumericVector calc_d5_method(LogicalVector d5_cands, NumericVector dx);
RcppExport SEXP _rdailychange_calc_d5_method(SEXP d5_candsSEXP, SEXP dxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type d5_cands(d5_candsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dx(dxSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_d5_method(d5_cands, dx));
    return rcpp_result_gen;
END_RCPP
}
// purge_d2_cands
LogicalVector purge_d2_cands(LogicalVector d2_cands);
RcppExport SEXP _rdailychange_purge_d2_cands(SEXP d2_candsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< LogicalVector >::type d2_cands(d2_candsSEXP);
    rcpp_result_gen = Rcpp::wrap(purge_d2_cands(d2_cands));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rdailychange_calc_d3_method", (DL_FUNC) &_rdailychange_calc_d3_method, 2},
    {"_rdailychange_calc_d4_method", (DL_FUNC) &_rdailychange_calc_d4_method, 2},
    {"_rdailychange_calc_d5_method", (DL_FUNC) &_rdailychange_calc_d5_method, 2},
    {"_rdailychange_purge_d2_cands", (DL_FUNC) &_rdailychange_purge_d2_cands, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_rdailychange(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
