# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_d3_method <- function(d3_cands, dx) {
    .Call(`_rdailychange_calc_d3_method`, d3_cands, dx)
}

calc_d4_method <- function(d4_cands, dx) {
    .Call(`_rdailychange_calc_d4_method`, d4_cands, dx)
}

calc_d5_method <- function(d5_cands, dx) {
    .Call(`_rdailychange_calc_d5_method`, d5_cands, dx)
}

purge_d2_cands <- function(d2_cands) {
    .Call(`_rdailychange_purge_d2_cands`, d2_cands)
}

